from __future__ import annotations

import portal_v8

UI=r'''
<style>
.rx-human-card{border:1px solid #315547;background:linear-gradient(145deg,#10271d,#0a1912);border-radius:14px;padding:12px 13px;margin:0 0 12px}
.rx-human-top{display:flex;align-items:center;justify-content:space-between;gap:8px;margin-bottom:7px}.rx-human-title{font-size:9px;font-weight:950;letter-spacing:.08em;text-transform:uppercase;color:#d7eee2}.rx-human-signal{display:inline-flex;align-items:center;gap:5px;border-radius:999px;padding:5px 8px;font-size:8px;font-weight:900}.rx-human-signal.ok{background:#163d29;color:#79efb2}.rx-human-signal.info{background:#173346;color:#8dd6ff}.rx-human-signal.warn{background:#413412;color:#ffd87b}.rx-human-signal.bad{background:#4a201d;color:#ffaaa1}.rx-human-signal.wait{background:#2b2c31;color:#c8cbd3}.rx-human-main{font-size:11px;line-height:1.55;color:#eef8f2;font-weight:760}.rx-human-why{font-size:9px;line-height:1.5;color:#9fb8ab;margin-top:6px}.rx-human-legend{display:flex;flex-wrap:wrap;gap:5px;margin-top:8px}.rx-human-chip{border:1px solid #29473a;border-radius:999px;padding:4px 7px;color:#a9c1b5;font-size:7px}.rx-tech-details{margin-top:9px;border-top:1px solid #1e382d;padding-top:8px}.rx-tech-details summary{cursor:pointer;color:#8ca89a;font-size:8px;font-weight:800}.rx-tech-details .rx-tech-body{padding-top:7px}.rx-readable-term{border-bottom:1px dotted #5d776a;cursor:help}.rx-mobile-hero .rx-human-card{margin-top:9px;margin-bottom:0;padding:9px}.rx-mobile-hero .rx-human-main{font-size:9px}.rx-mobile-hero .rx-human-why{font-size:8px}
@media(max-width:720px){.rx-human-card{padding:10px}.rx-human-main{font-size:10px}.rx-human-why{font-size:8px}}
</style>
<script>
(function(){
 const q=s=>document.querySelector(s),qa=s=>Array.from(document.querySelectorAll(s));
 const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
 const txt=(el)=>String(el?.textContent||'').replace(/\s+/g,' ').trim();
 function cur(){try{return (typeof current!=='undefined'&&current)?current:window.current||{}}catch(e){return window.current||{}}}
 function humanStatus(raw){const s=String(raw||'').trim().toLowerCase();if(!s||s==='—')return {label:'SEM INFORMAÇÃO',kind:'wait'};if(/ativo|regular|aprov|inscrit|valid|ok/.test(s))return {label:'SEM ALERTA APARENTE',kind:'ok'};if(/cancel|susp|pend|irregular|bloq|embarg|problema/.test(s))return {label:'ATENÇÃO',kind:'warn'};if(/process|carreg|consult|analis/.test(s))return {label:'PROCESSANDO',kind:'wait'};return {label:String(raw).toUpperCase(),kind:'info'}}
 function card(kind,label,main,why,chips=[]){return `<div class="rx-human-card" data-rx-human="1"><div class="rx-human-top"><div class="rx-human-title">LEITURA RÁPIDA</div><span class="rx-human-signal ${kind}">${esc(label)}</span></div><div class="rx-human-main">${esc(main)}</div>${why?`<div class="rx-human-why">${esc(why)}</div>`:''}${chips.length?`<div class="rx-human-legend">${chips.map(x=>`<span class="rx-human-chip">${esc(x)}</span>`).join('')}</div>`:''}</div>`}
 function kpiMap(p){const out={};p?.querySelectorAll('.rx-kpi').forEach(k=>{const s=k.querySelectorAll('small'),b=k.querySelector('b');if(s[0])out[txt(s[0])]={value:txt(b),note:txt(s[1])}});return out}
 function nFrom(v){const m=String(v||'').replace(/\./g,'').replace(',','.').match(/-?\d+(?:\.\d+)?/);return m?Number(m[0]):null}
 function overallSummary(){const p=cur(),st=humanStatus(p.status),area=Number(String(p.area_ha??'').replace(',','.'));const a=Number.isFinite(area)?area.toLocaleString('pt-BR',{maximumFractionDigits:2})+' hectares':'área não informada';const muni=[p.municipality,p.uf].filter(Boolean).join('/');return card(st.kind,st.label,`Imóvel de ${a}${muni?' em '+muni:''}. Cadastro Ambiental Rural: ${p.status||'situação não informada'}.`,`O código do CAR identifica o cadastro. A situação cadastral não substitui análise ambiental, dominial ou de campo.`,['CAR = Cadastro Ambiental Rural','ha = hectares'])}
 function climateSummary(p){const m=kpiMap(p),rain=m['Chuva']?.value,temp=m['Temp. média']?.value,tri=m['Triagem']?.value;let kind='info',label='CONTEXTO CLIMÁTICO';if(tri&&/seca|aten|alto|cr[ií]tic/i.test(tri)){kind='warn';label='ATENÇÃO CLIMÁTICA'}const main=rain?`No período selecionado, a área recebeu cerca de ${rain}${temp?' e teve temperatura média de '+temp:''}.`:`Os dados mostram chuva e temperatura no ponto representativo do imóvel.`;return card(kind,label,main,`Esses números ajudam a entender o contexto recente. Para dizer se há seca ou anomalia, compare com a climatologia e use a aba “Análise de secas”.`,['mm = milímetros de chuva','°C = temperatura'])}
 function waterSummary(p){const m=kpiMap(p),w=nFrom(m['Poços próximos']?.value),depth=m['Profundidade mediana']?.value,evidence=m['Evidência']?.value;let kind=w===0?'warn':'info',label=w===0?'POUCA EVIDÊNCIA LOCAL':'HÁ REGISTROS NO ENTORNO';const main=w===null?`A consulta procura poços cadastrados ao redor do imóvel.`:`Foram encontrados ${w} poço(s) cadastrado(s) no raio pesquisado${depth&&depth!=='—'?', com profundidade mediana de '+depth:''}.`;return card(kind,label,main,`Isso mostra o comportamento regional da água subterrânea. Não garante vazão, qualidade ou disponibilidade dentro desta fazenda sem estudo local.`,evidence&&evidence!=='—'?[`Evidência informada: ${evidence}`]:[])}
 function embargoSummary(p){const m=kpiMap(p);const vals=['Embargos IBAMA','Embargos ICMBio','Autos IBAMA'].map(k=>({k,v:m[k]?.value,n:nFrom(m[k]?.value)}));const processing=vals.some(x=>/process|parcial/i.test(x.v||''));const hits=vals.filter(x=>x.n!=null).reduce((a,x)=>a+x.n,0);let kind='ok',label='SEM OCORRÊNCIA NAS FONTES CONSULTADAS',main='Nenhum registro foi retornado nas consultas que responderam.';if(hits>0){kind='bad';label='HÁ REGISTRO DE FISCALIZAÇÃO';main=`Foram retornados ${hits} registro(s) entre embargos e autos. É necessário abrir os detalhes antes de qualquer decisão.`}else if(processing){kind='wait';label='CONSULTA AINDA INCOMPLETA';main='Parte das fontes ainda está processando ou respondeu parcialmente. Não trate isso como ausência de embargo.'}return card(kind,label,main,`“Zero” só significa nenhuma ocorrência encontrada nas fontes que efetivamente responderam. Fonte indisponível nunca equivale a imóvel regular.`)}
 function cropsSummary(p){return card('info','CONTEXTO REGIONAL',`Esta aba mostra o que é produzido no município e ajuda a entender a vocação agrícola da região.`,`Os dados não provam que esta fazenda produza essas culturas. Eles são municipais, não do imóvel.`,['Município ≠ fazenda'])}
 function docsSummary(p){const cards=Array.from(p.querySelectorAll('.rx-card')),active=cards.filter(x=>/ATIVO/i.test(txt(x))).length,off=cards.filter(x=>/PREPARADO.*OFF/i.test(txt(x))).length;return card(active?'info':'wait',active?'HÁ FONTES ATIVAS':'INTEGRAÇÕES PREPARADAS',active?`${active} integração(ões) documental(is) está(ão) ativa(s).${off?' Outras '+off+' estão preparadas, mas desligadas.':''}`:`As fontes documentais estão preparadas, mas ainda não estão todas habilitadas.`,`“Preparado — OFF” significa que a integração existe no sistema, porém não está consultando dados agora.`)}
 function miningSummary(p){const m=kpiMap(p),proc=nFrom(m['Processos ANM']?.value)||0,rare=m['Terras raras']?.value||'';let kind='ok',label='SEM SINAL ESPECÍFICO',main='Nenhum sinal específico relevante foi indicado pelas fontes que responderam.';if(proc>0){kind='warn';label='HÁ PROCESSO MINERÁRIO';main=`Há ${proc} processo(s) minerário(s) intersectando a área consultada. Isso merece verificação do tipo, fase e substância.`}if(/SINAL/i.test(rare)&&!/SEM SINAL/i.test(rare)){kind='warn';label='SINAL GEOLÓGICO';main+=' Também houve sinal relacionado a terras raras.'}return card(kind,label,main,`Processo ANM ou ocorrência geológica não significa existência de jazida economicamente viável. É uma triagem para aprofundar a análise.`,['ANM = Agência Nacional de Mineração','SGB = Serviço Geológico do Brasil'])}
 function agroSummary(p){const cards=p.querySelectorAll('.rx-card').length;return card('info','CONTEXTO AGROPECUÁRIO',cards?`Há dados regionais de rebanhos e cadeia produtiva disponíveis para o município.`:`A aba busca dados regionais de produção e cadeia agropecuária.`,`Esses números descrevem o município/entorno. Eles não devem ser apresentados como produção ou rebanho desta fazenda.`,['SIF = Serviço de Inspeção Federal','Município ≠ fazenda'])}
 function generalSummary(p){return overallSummary()}
 function summarizePane(p){if(!p||p.querySelector('[data-rx-human="1"]'))return;const id=p.id||'';let html='';if(id==='rxPane-clima')html=climateSummary(p);else if(id==='rxPane-agua')html=waterSummary(p);else if(id==='rxPane-embargos')html=embargoSummary(p);else if(id==='rxPane-safras')html=cropsSummary(p);else if(id==='rxPane-certidoes')html=docsSummary(p);else if(id==='rxPane-mineracao')html=miningSummary(p);else if(id==='rxPane-agro')html=agroSummary(p);if(html&&p.querySelector('h3'))p.insertAdjacentHTML('afterbegin',html);wrapSources(p)}
 function wrapSources(root){root?.querySelectorAll('.rx-source').forEach(s=>{if(s.closest('.rx-tech-details'))return;const d=document.createElement('details');d.className='rx-tech-details';d.innerHTML='<summary>Ver fonte e detalhe técnico</summary><div class="rx-tech-body"></div>';s.parentNode.insertBefore(d,s);d.querySelector('.rx-tech-body').appendChild(s)})}
 function enhanceMobile(){const hero=q('.rx-mobile-hero');if(!hero||hero.querySelector('[data-rx-human="1"]'))return;hero.insertAdjacentHTML('beforeend',overallSummary())}
 function improveLabels(){qa('.rx-mobile-kpi small').forEach(x=>{if(txt(x)==='CAR')x.textContent='Cadastro CAR'});qa('.rx-mobile-actions .primary').forEach(x=>{if(/ABRIR ANÁLISE COMPLETA/i.test(txt(x)))x.textContent='VER ANÁLISE COMPLETA'});qa('.rx-mobile-actions button').forEach(x=>{if(txt(x)==='PDF')x.textContent='RELATÓRIO PDF'})}
 function run(){enhanceMobile();improveLabels();qa('.rx-tab-pane').forEach(summarizePane);const body=q('#pbody');if(body&&!body.classList.contains('rx-tab-mode')&&!body.querySelector(':scope > [data-rx-human="1"]')&&cur()?.car_code){const nav=q('#rxPropertyTabs');if(nav)nav.insertAdjacentHTML('afterend',generalSummary(body))}wrapSources(body)}
 let t;const schedule=()=>{clearTimeout(t);t=setTimeout(run,60)};
 const obs=new MutationObserver(schedule);function start(){obs.observe(document.body,{subtree:true,childList:true,characterData:true});schedule()}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();
</script>
'''

if 'RX_HUMAN_READING_V23' not in portal_v8.PORTAL_HTML:
    portal_v8.PORTAL_HTML=portal_v8.PORTAL_HTML.replace('</body>',UI+'<!-- RX_HUMAN_READING_V23 --></body>')

print('RX_HUMAN_READING_V23=plain_language_decision_layer',flush=True)
