from __future__ import annotations

import portal_v8

UI=r'''
<style>
.rx-rare-mode{position:absolute;z-index:1760;left:14px;bottom:18px;background:rgba(28,12,42,.96);border:1px solid #a76cff;border-radius:14px;padding:10px 12px;color:#f1e7ff;box-shadow:0 0 35px #a65cff55;display:none;min-width:240px;max-width:320px}.rx-rare-mode.show{display:block}.rx-rare-head{display:flex;align-items:center;gap:9px}.rx-rare-gem{width:27px;height:27px;position:relative;display:inline-block;filter:drop-shadow(0 0 8px #cb8cff)}.rx-rare-gem:before{content:'';position:absolute;inset:4px;transform:rotate(45deg);background:linear-gradient(135deg,#f1c8ff,#b05cff 45%,#6522a9);border:1px solid #f4d8ff;border-radius:4px}.rx-rare-mode b{font-size:10px}.rx-rare-mode small{display:block;color:#c9afd9;font-size:8px;margin-top:2px}.rx-rare-count{margin-left:auto;border-radius:999px;background:#d793ff;color:#24102f;padding:4px 7px;font-size:9px;font-weight:950}.rx-rare-legend{margin-top:8px;border-top:1px solid #694584;padding-top:7px;font-size:8px;line-height:1.5;color:#d7c5e2}.rx-rare-marker{width:30px;height:30px;position:relative;filter:drop-shadow(0 0 9px #d489ff)}.rx-rare-marker i{position:absolute;width:20px;height:20px;left:5px;top:5px;transform:rotate(45deg);background:linear-gradient(135deg,#ffd7ff,#c567ff 45%,#661cb1);border:2px solid #fff;border-radius:5px}.rx-rare-marker strong{position:absolute;z-index:2;inset:0;display:grid;place-items:center;color:#fff;font-size:7px;font-weight:950;text-shadow:0 1px 3px #2c103c}.rx-rare-interest{margin-top:7px;max-height:110px;overflow:auto;font-size:8px}.rx-rare-interest div{padding:4px 0;border-bottom:1px solid #56366d}.leaflet-interactive.rx-rare-poly{filter:drop-shadow(0 0 5px #be68ff)}
@media(max-width:720px){.rx-rare-mode{left:10px;right:10px;bottom:12px;max-width:none}}
</style>
<script>
(function(){
let markerLayer=null,lastCount=0,autoFitDone=false;
const q=s=>document.querySelector(s);
function m(){try{return (typeof map!=='undefined'&&map&&map.getBounds)?map:null}catch(e){return null}}
function icon(){return L.divIcon({className:'',html:'<div class="rx-rare-marker"><i></i><strong>TR</strong></div>',iconSize:[30,30],iconAnchor:[15,15],popupAnchor:[0,-13]})}
function center(g){try{const l=L.geoJSON(g);return l.getBounds().getCenter()}catch(e){return null}}
function ensurePanel(){let p=q('#rxRareMode');if(p)return p;const main=q('.main');if(!main)return null;p=document.createElement('div');p.id='rxRareMode';p.className='rx-rare-mode';p.innerHTML='<div class="rx-rare-head"><span class="rx-rare-gem"></span><div><b>TERRAS RARAS</b><small>áreas de interesse / sinais</small></div><span id="rxRareCount" class="rx-rare-count">0</span></div><div class="rx-rare-legend">◆ roxo = processo/área relacionada ao filtro<br>◆ brilho forte = sinal destacado no mapa<br><b>Não significa jazida comprovada.</b></div><div id="rxRareInterest" class="rx-rare-interest"></div>';main.appendChild(p);return p}
function clear(){const mm=m();if(markerLayer&&mm)mm.removeLayer(markerLayer);markerLayer=null;lastCount=0;autoFitDone=false;const p=ensurePanel();if(p)p.classList.remove('show')}
async function refresh(){const mm=m(),tog=q('#rxMineralToggle'),sel=q('#rxMineralSelect'),panel=ensurePanel();if(!mm||!tog||!sel||!panel)return;if(!tog.checked||sel.value!=='terras_raras'){clear();return}panel.classList.add('show');const b=mm.getBounds(),span=Math.max(b.getEast()-b.getWest(),b.getNorth()-b.getSouth());q('#rxRareCount').textContent=span>8?'SGB':'…';q('#rxRareInterest').innerHTML=span>8?'<div>Aproxime o mapa para ver processos ANM com símbolos.</div>':'<div>Consultando processos ANM…</div>';if(span>8)return;try{const u=new URL('/v1/map/minerals/anm',location.origin);u.searchParams.set('west',b.getWest());u.searchParams.set('south',b.getSouth());u.searchParams.set('east',b.getEast());u.searchParams.set('north',b.getNorth());u.searchParams.set('mineral','terras_raras');u.searchParams.set('limit','250');const r=await fetch(u),d=await r.json();if(!r.ok)throw new Error(d.detail||'ANM indisponível');if(markerLayer)mm.removeLayer(markerLayer);markerLayer=L.layerGroup().addTo(mm);const interests=[];(d.features||[]).forEach((f,i)=>{const c=center(f.geometry);if(!c)return;const p=f.properties||{};const label=Object.entries(p).filter(([k,v])=>v!=null&&k!=='rx_minerals').slice(0,7).map(([k,v])=>`<b>${k}</b>: ${v}`).join('<br>');L.marker(c,{icon:icon(),zIndexOffset:700}).bindPopup(`<b>◆ Sinal relacionado a terras raras</b><br>${label}<br><small>ANM + filtro mineral. Não comprova jazida.</small>`).addTo(markerLayer);interests.push(p.processo||p.Processo||p.numero||p.substancia||('Sinal '+(i+1)))});lastCount=(d.features||[]).length;q('#rxRareCount').textContent=String(lastCount);q('#rxRareInterest').innerHTML=lastCount?interests.slice(0,8).map(x=>`<div>◆ ${String(x).slice(0,85)}</div>`).join(''):'<div>Nenhum processo ANM relacionado neste enquadramento. As camadas geológicas do SGB continuam visíveis.</div>';if(lastCount&&markerLayer&&!autoFitDone){const bounds=L.featureGroup(markerLayer.getLayers()).getBounds();if(bounds.isValid()){autoFitDone=true;mm.fitBounds(bounds.pad(.22),{maxZoom:11,animate:true})}}}catch(e){q('#rxRareCount').textContent='!';q('#rxRareInterest').innerHTML='<div>Fonte parcial: '+e.message+'</div>'}}
function install(){const mm=m(),tog=q('#rxMineralToggle'),sel=q('#rxMineralSelect');if(!mm||!tog||!sel){setTimeout(install,300);return}ensurePanel();tog.addEventListener('change',()=>{autoFitDone=false;setTimeout(refresh,150)});sel.addEventListener('change',()=>{autoFitDone=false;setTimeout(refresh,150)});let t;const sched=()=>{clearTimeout(t);t=setTimeout(refresh,600)};mm.on('moveend',sched);mm.on('zoomend',sched)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();
</script>
'''

if 'rxRareMode' not in portal_v8.PORTAL_HTML:
    portal_v8.PORTAL_HTML=portal_v8.PORTAL_HTML.replace('</body>',UI+'</body>')

print('RX_RARE_EARTH_SYMBOLS=gem_markers_counter_legend_autofit',flush=True)
