from __future__ import annotations

import portal_v8

UI = r'''
<style id="rxPropertyBrowserV44Style">
:root{--rx-browser-w:320px}
.rx-property-browser{position:absolute;z-index:830;left:0;top:0;bottom:0;width:var(--rx-browser-w);display:flex;flex-direction:column;background:rgba(5,19,13,.985);border-right:1px solid rgba(99,230,165,.18);box-shadow:18px 0 42px rgba(0,0,0,.25);backdrop-filter:blur(14px);overflow:hidden}
.rx-property-browser-head{padding:14px 13px 11px;border-bottom:1px solid rgba(99,230,165,.13);background:linear-gradient(180deg,rgba(12,37,26,.96),rgba(7,24,17,.92))}.rx-property-title{display:flex;align-items:center;justify-content:space-between;gap:8px}.rx-property-title b{font-size:12px;letter-spacing:.06em}.rx-property-count{min-width:30px;height:24px;padding:0 8px;border-radius:999px;display:grid;place-items:center;background:#63e6a5;color:#052116;font-size:9px;font-weight:950}.rx-property-sub{display:block;margin-top:4px;color:#88a797;font-size:8.5px;line-height:1.4}.rx-property-filter{width:100%;height:35px;margin-top:9px;padding:0 10px;border:1px solid #294b3c;border-radius:10px;background:#081a12;color:#eef8f2;outline:0;font-size:9.5px}.rx-property-filter:focus{border-color:#63e6a5}
.rx-property-list{flex:1;overflow:auto;padding:8px}.rx-property-item{width:100%;display:grid;grid-template-columns:29px minmax(0,1fr);gap:8px;padding:9px;margin:0 0 6px;border:1px solid rgba(62,109,87,.52);border-radius:12px;background:rgba(9,29,20,.76);color:#eef8f2;text-align:left;cursor:pointer;transition:.15s ease}.rx-property-item:hover{border-color:rgba(99,230,165,.62);background:rgba(13,40,28,.94);transform:translateY(-1px)}.rx-property-item.active{border-color:#63e6a5;background:linear-gradient(145deg,rgba(16,60,41,.96),rgba(9,34,24,.98));box-shadow:0 0 0 1px rgba(99,230,165,.1)}.rx-property-index{width:29px;height:29px;border-radius:9px;display:grid;place-items:center;background:#0d2a1d;border:1px solid #2b5542;color:#7dd7aa;font-size:8.5px;font-weight:900}.rx-property-item.active .rx-property-index{background:#63e6a5;color:#052116;border-color:#63e6a5}.rx-property-name{display:block;font-size:10.5px;font-weight:900;line-height:1.25;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.rx-property-meta{display:flex;gap:6px;flex-wrap:wrap;margin-top:4px;color:#9bb1a6;font-size:8px}.rx-property-car{margin-top:4px;color:#6e9381;font:700 7px/1.2 ui-monospace,SFMono-Regular,Menlo,monospace;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.rx-property-dot{display:inline-block;width:6px;height:6px;border-radius:50%;background:#63e6a5;margin-right:5px}.rx-property-empty{padding:26px 15px;text-align:center;color:#8da89a;font-size:9.5px;line-height:1.5}.rx-property-empty b{display:block;color:#e6f8ee;margin-bottom:4px}.rx-property-foot{padding:7px 11px;border-top:1px solid rgba(99,230,165,.1);color:#668877;font-size:7.5px}.rx-property-toggle{display:none}
@media(min-width:901px){.main>.map,#map.map{margin-left:var(--rx-browser-w)!important;width:calc(100% - var(--rx-browser-w))!important}.main>#rxMapState{left:calc(var(--rx-browser-w) + 14px)!important}.main>.hint{left:calc(var(--rx-browser-w) + 14px)!important}.rx-city-results{left:calc(var(--rx-browser-w) + 16px)!important}}
@media(max-width:900px){.rx-property-browser{left:8px;right:8px;top:auto;bottom:8px;width:auto;height:min(58vh,500px);border:1px solid #2d5543;border-radius:17px;box-shadow:0 18px 55px rgba(0,0,0,.48);transform:translateY(calc(100% - 49px));transition:transform .2s ease;z-index:880}.rx-property-browser.expanded{transform:translateY(0)}.rx-property-browser-head{padding:10px 11px 8px}.rx-property-sub,.rx-property-filter,.rx-property-list,.rx-property-foot{display:none}.rx-property-browser.expanded .rx-property-sub,.rx-property-browser.expanded .rx-property-filter,.rx-property-browser.expanded .rx-property-list{display:block}.rx-property-toggle{display:grid;width:27px;height:27px;place-items:center;border:1px solid #315b48;border-radius:9px;background:#0b2519;color:#dff8e9;font-size:14px;cursor:pointer}body.rx43-dossier-open .rx-property-browser{display:none!important}}
</style>
<script>
(function(){
  let items=[],selected='',filter='';
  const q=s=>document.querySelector(s), norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
  function m(){try{return (typeof map!=='undefined'&&map&&map.eachLayer)?map:null}catch(e){return null}}
  function props(f){const p=f?.properties||{};let name='';for(const k of ['nome_imovel','denominacao','nome_area','nome_fazenda','fazenda','nome_propriedade']){const v=String(p[k]||'').trim();if(v.length>2&&!/^im[oó]vel rural$/i.test(v)){name=v;break}}return {car_code:String(p.cod_imovel||p.car_code||'').toUpperCase(),name,municipality:p.municipio||p.municipality||'',uf:p.uf||'',area_ha:p.area??p.area_ha,status:p.status_imovel||p.status||'',feature:f}}
  function scan(){const mm=m();if(!mm)return[];const by=new Map();mm.eachLayer(layer=>{const f=layer?.feature,code=String(f?.properties?.cod_imovel||f?.properties?.car_code||'').toUpperCase();if(!code||by.has(code))return;const x=props(f);x.layer=layer;by.set(code,x)});return [...by.values()].sort((a,b)=>(a.name||a.municipality||a.car_code).localeCompare(b.name||b.municipality||b.car_code,'pt-BR'))}
  function publicNameMap(){const out=new Map();try{document.querySelectorAll('.rx-farm-name-label').forEach(el=>{const txt=(el.getAttribute('title')||el.textContent||'').trim();if(txt)out.set(norm(txt),txt)})}catch(e){}return out}
  function ensure(){let host=q('#rxPropertyBrowser');if(host)return host;host=document.createElement('aside');host.id='rxPropertyBrowser';host.className='rx-property-browser';host.innerHTML='<div class="rx-property-browser-head"><div class="rx-property-title"><b>FAZENDAS NESTA ÁREA</b><div style="display:flex;gap:7px;align-items:center"><span id="rxPropertyCount" class="rx-property-count">0</span><button id="rxPropertyToggle" class="rx-property-toggle" type="button">⌃</button></div></div><small class="rx-property-sub">Lista sincronizada com o mapa. Clique para localizar e abrir o imóvel.</small><input id="rxPropertyFilter" class="rx-property-filter" placeholder="Filtrar fazenda, CAR ou município"></div><div id="rxPropertyList" class="rx-property-list"></div><div class="rx-property-foot">Fonte territorial: SICAR/CAR público · nomes somente quando confirmados por fonte pública segura.</div>';q('.main')?.appendChild(host);q('#rxPropertyToggle').onclick=()=>host.classList.toggle('expanded');q('#rxPropertyFilter').oninput=e=>{filter=e.target.value||'';render()};return host}
  function displayName(x){return x.name||'Imóvel rural — nome não confirmado'}
  function render(){ensure();const list=q('#rxPropertyList'),count=q('#rxPropertyCount');if(!list||!count)return;const f=norm(filter);const shown=items.filter(x=>!f||norm([x.name,x.car_code,x.municipality,x.uf].join(' ')).includes(f));count.textContent=String(shown.length);if(!shown.length){list.innerHTML='<div class="rx-property-empty"><b>Nenhum imóvel listado aqui.</b>Mova ou aproxime o mapa para carregar os imóveis rurais.</div>';return}list.innerHTML='';shown.forEach((x,i)=>{const b=document.createElement('button');b.type='button';b.className='rx-property-item'+(x.car_code===selected?' active':'');b.title=x.car_code;b.innerHTML=`<span class="rx-property-index">${i+1}</span><span><span class="rx-property-name">${x.name?'<span class="rx-property-dot"></span>':''}${displayName(x)}</span><span class="rx-property-meta"><span>${x.municipality||'—'}${x.uf?' / '+x.uf:''}</span><span><strong>${x.area_ha??'—'} ha</strong></span></span><span class="rx-property-car">${x.car_code}</span></span>`;b.onclick=()=>select(x);list.appendChild(b)})}
  function select(x){selected=x.car_code;render();const mm=m();try{const target=x.layer?.getBounds?x.layer:x.layer?x.layer:null;if(target?.getBounds){const b=target.getBounds();if(b?.isValid())mm.fitBounds(b.pad(.35),{maxZoom:16,animate:true})}else if(x.layer?.getLatLng)mm.panTo(x.layer.getLatLng())}catch(e){}setTimeout(()=>{try{if(typeof showProperty==='function')showProperty({car_code:x.car_code,municipality:x.municipality,uf:x.uf,area_ha:x.area_ha,status:x.status,name:x.name},x.feature?.geometry)}catch(e){}},220);if(matchMedia('(max-width:900px)').matches)q('#rxPropertyBrowser')?.classList.remove('expanded')}
  function refresh(){ensure();const next=scan();const sig=next.map(x=>x.car_code).join('|');const old=items.map(x=>x.car_code).join('|');if(sig!==old){items=next;window.rxVisiblePropertiesV44=items.map(({layer,feature,...x})=>x);render()}else if(!items.length)render()}
  function install(){const mm=m();if(!mm){setTimeout(install,300);return}ensure();mm.on('layeradd',()=>setTimeout(refresh,80));mm.on('layerremove',()=>setTimeout(refresh,80));mm.on('moveend',()=>setTimeout(refresh,120));mm.on('zoomend',()=>setTimeout(refresh,120));setInterval(refresh,2500);setTimeout(refresh,700)}
  window.rxRefreshPropertyBrowser=refresh;window.rxSelectVisiblePropertyV44=code=>{const x=items.find(i=>i.car_code===String(code||'').toUpperCase());if(x)select(x)};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();
</script>
<!-- RX_PROPERTY_BROWSER_V44 -->
'''

if 'RX_PROPERTY_BROWSER_V44' not in portal_v8.PORTAL_HTML:
    portal_v8.PORTAL_HTML = portal_v8.PORTAL_HTML.replace('</body>', UI + '</body>')

print('RX_PROPERTY_BROWSER_V44=synchronized_map_property_sidebar', flush=True)
