from __future__ import annotations

"""V47 lazy CAR-integrity UI extension.

This module deliberately does not edit the frozen V45 renderer. It attaches after
V45 and before V46, wraps the public ``showProperty`` entry point, and injects the
Block-2 slot only after the dossier is actually opened.
"""

import portal_v8


V47_INTEGRITY_UI = r'''
<style id="rxCarIntegrityV47Style">
.rx45-integrity-slot{min-width:0}.rx45-integrity-head{display:flex;justify-content:space-between;gap:8px;align-items:center;margin-bottom:7px}.rx45-integrity-badge{font-size:7px;font-weight:900;color:var(--rx45-muted);text-transform:uppercase;letter-spacing:.45px}
.rx45-integrity-reading{padding:9px 10px;border-radius:10px;border:1px solid #28513e;border-left:4px solid var(--rx45-green);background:#0c1d16;font-size:8.5px;line-height:1.5;font-weight:800;margin-bottom:8px}.rx45-integrity-reading.alert{border-left-color:var(--rx45-red);border-color:#60352c;background:#241511}.rx45-integrity-reading.partial{border-left-color:var(--rx45-yellow);border-color:#5b4925;background:#211b0f}
.rx45-integrity-checks{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:6px;margin-bottom:7px}.rx45-integrity-check{min-width:0;padding:8px;border-radius:10px;border:1px solid #1d382c;background:#0c1d16}.rx45-integrity-check.clear{border-top:2px solid var(--rx45-green)}.rx45-integrity-check.alert{border-top:2px solid var(--rx45-red)}.rx45-integrity-check.partial{border-top:2px solid var(--rx45-yellow)}.rx45-integrity-check small{display:block;color:var(--rx45-muted);font-size:6.5px;line-height:1.3;text-transform:uppercase;letter-spacing:.35px;overflow-wrap:anywhere}.rx45-integrity-check b{display:block;color:var(--rx45-text);font-size:9px;line-height:1.35;margin-top:4px;overflow-wrap:anywhere}.rx45-integrity-check span{display:block;color:var(--rx45-muted);font-size:7px;line-height:1.35;margin-top:3px;overflow-wrap:anywhere}
.rx45-integrity-snapshot{font-size:7px;color:var(--rx45-muted);margin:2px 0 8px}.rx45-integrity-snapshot b{color:#d8e9df;font-weight:850}
.rx45-integrity-scroll{width:100%;min-width:0;overflow-x:auto;overscroll-behavior-x:contain}.rx45-integrity-table{width:100%;border-collapse:separate;border-spacing:0;table-layout:fixed;border:1px solid #1d382c;border-radius:9px;overflow:hidden;background:#091a13}.rx45-integrity-table th,.rx45-integrity-table td{padding:6px 5px;border-right:1px solid #1d382c;border-top:1px solid #1d382c;font-size:6.6px;line-height:1.35;text-align:left;vertical-align:top;overflow-wrap:anywhere;word-break:normal}.rx45-integrity-table th:last-child,.rx45-integrity-table td:last-child{border-right:0}.rx45-integrity-table thead th{border-top:0;background:#0c1d16;color:var(--rx45-muted);font-weight:900;text-transform:uppercase;letter-spacing:.2px}.rx45-integrity-table thead th:first-child{width:25%}.rx45-integrity-table tbody th{font-weight:800;color:#d8e9df}.rx45-integrity-note{font-size:7px;line-height:1.45;color:var(--rx45-muted);margin-top:7px}.rx45-integrity-unavailable{padding:9px;border-radius:10px;background:#0c1d16;border-left:3px solid var(--rx45-gray);font-size:8px;line-height:1.45;color:var(--rx45-muted)}
.rx47-pending-row{display:flex;align-items:center;justify-content:space-between;gap:8px}
@media(max-width:480px){.rx45-integrity-checks{grid-template-columns:1fr}.rx45-integrity-reading{font-size:9px}.rx45-integrity-check{padding:8px 9px}.rx45-integrity-check small{font-size:7px}.rx45-integrity-check b{font-size:9.5px}.rx45-integrity-check span{font-size:7.5px}.rx45-integrity-scroll{overflow-x:visible}.rx45-integrity-table,.rx45-integrity-table tbody,.rx45-integrity-table tr,.rx45-integrity-table th,.rx45-integrity-table td{display:block;width:100%!important}.rx45-integrity-table{border:0;background:transparent;overflow:visible}.rx45-integrity-table thead{display:none}.rx45-integrity-table tbody{display:grid;gap:7px}.rx45-integrity-table tbody tr{border:1px solid #1d382c;border-radius:10px;overflow:hidden;background:#091a13}.rx45-integrity-table tbody th{padding:7px 8px;border:0;background:#0c1d16;font-size:8.5px}.rx45-integrity-table tbody td{padding:7px 8px;border:0;border-top:1px solid #1d382c;font-size:8px;line-height:1.4;min-width:0;white-space:normal;overflow:visible;text-overflow:clip}.rx45-integrity-table tbody td::before{content:attr(data-label);display:block;color:var(--rx45-muted);font-size:6.5px;font-weight:900;text-transform:uppercase;letter-spacing:.3px;margin-bottom:2px}}
</style>
<script id="rxCarIntegrityV47">
(()=>{
 const q=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
 const fmt=(v,d=2)=>{const n=Number(v);return Number.isFinite(n)?n.toLocaleString('pt-BR',{minimumFractionDigits:d,maximumFractionDigits:d}):'Indisponível'};
 const datePt=v=>{const m=String(v||'').match(/^(\d{4})-(\d{2})-(\d{2})/);return m?`${m[3]}/${m[2]}/${m[1]}`:(String(v||'').trim()||'Não informado')};
 const UF_NAMES={AC:'Acre',AL:'Alagoas',AP:'Amapá',AM:'Amazonas',BA:'Bahia',CE:'Ceará',DF:'Distrito Federal',ES:'Espírito Santo',GO:'Goiás',MA:'Maranhão',MT:'Mato Grosso',MS:'Mato Grosso do Sul',MG:'Minas Gerais',PA:'Pará',PB:'Paraíba',PR:'Paraná',PE:'Pernambuco',PI:'Piauí',RJ:'Rio de Janeiro',RN:'Rio Grande do Norte',RS:'Rio Grande do Sul',RO:'Rondônia',RR:'Roraima',SC:'Santa Catarina',SP:'São Paulo',SE:'Sergipe',TO:'Tocantins'};
 const currentCar=()=>String((window.current||{}).car_code||'').trim().toUpperCase();
 function locationContext(d,car){const card=q(`.rx45-panel-card[data-car="${CSS.escape(car)}"]`),raw=String(card?.querySelector('.rx45-place')?.textContent||'').trim(),uf=String(d?.property?.sigla_uf||car.slice(0,2)||'').trim().toUpperCase();let municipality='';if(raw){const parts=raw.split(/\s*[\/·]\s*/).filter(Boolean);municipality=String(parts[0]||'').trim()}if(/n[aã]o informad/i.test(municipality)||/^\d+$/.test(municipality))municipality='';const placeLabel=municipality?`${municipality}/${uf}`:'';return{municipality,uf,placeLabel,stateLabel:UF_NAMES[uf]||uf||'estado cadastrado'}}
 function boundaryCard(x,title){if(!x||x.state!=='checked')return{tone:'partial',title,value:'Indisponível',detail:'Checagem não concluída'};const a=Number(x.outside_ha),p=Number(x.outside_pct),outside=Boolean(x.has_outside_area)||Number.isFinite(a)&&a>0.000001;return{tone:outside?'alert':'clear',title,value:outside?'Fora do limite':'Dentro do limite',detail:`${fmt(a,4)} ha fora · ${fmt(p,2)}%`}}
 function reading(d,loc){const ov=d.overlap||{},mb=d.municipality_boundary||{},ub=d.uf_boundary||{},complete=ov.state==='checked'&&mb.state==='checked'&&ub.state==='checked';if(!complete)return{tone:'partial',text:'Leitura parcial: uma ou mais checagens cadastrais não puderam ser concluídas. Nenhuma ausência foi presumida.'};const issues=[],count=Number(ov.distinct_car_count||0),area=Number(ov.union_area_ha||0),pct=Number(ov.property_pct||0);if(count>0&&area>0){issues.push(`Sobrepõe ${count} ${count===1?'CAR':'CARs'} em ${fmt(area,4)} ha (${fmt(pct,2)}% do imóvel).`)}const ma=Number(mb.outside_ha||0),mp=Number(mb.outside_pct||0);if(Boolean(mb.has_outside_area)||ma>0.000001)issues.push(`Possui ${fmt(ma,4)} ha (${fmt(mp,2)}%) fora ${loc.placeLabel?'de '+loc.placeLabel:'do município cadastrado'}.`);const ua=Number(ub.outside_ha||0),up=Number(ub.outside_pct||0);if(Boolean(ub.has_outside_area)||ua>0.000001)issues.push(`Possui ${fmt(ua,4)} ha (${fmt(up,2)}%) fora de ${loc.stateLabel}${loc.uf?` (${loc.uf})`:''}.`);return issues.length?{tone:'alert',text:issues.join(' ')}:{tone:'clear',text:`Nenhuma inconsistência cadastral: o imóvel não se sobrepõe a outro CAR e está inteiramente dentro ${loc.placeLabel?'de '+loc.placeLabel:'do município cadastrado'}.`}}
 function body(d){
   if(!d?.ok){return `<div class="rx45-integrity-unavailable" data-rx-integrity-pending="1"><strong>Consulta pendente</strong><br>A base oficial não respondeu agora. Nenhum resultado foi presumido.</div>`}
   const car=currentCar(),loc=locationContext(d,car),read=reading(d,loc),ov=d.overlap||{},rows=d.table_rows||[],count=Number(ov.distinct_car_count||0),oa=Number(ov.union_area_ha),op=Number(ov.property_pct),ovChecked=ov.state==='checked';
   const overlap={tone:ovChecked?(count>0?'alert':'clear'):'partial',title:'Sobreposição CAR × CAR',value:ovChecked?(count>0?`${count} ${count===1?'CAR':'CARs'}`:'Nenhuma'):'Indisponível',detail:ovChecked?`${fmt(oa,4)} ha · ${fmt(op,2)}% do imóvel`:'Checagem não concluída'};
   const municipality=boundaryCard(d.municipality_boundary,`Município${loc.placeLabel?' · '+loc.placeLabel:''}`),state=boundaryCard(d.uf_boundary,`Estado · ${loc.stateLabel}${loc.uf?` (${loc.uf})`:''}`);
   const check=x=>`<div class="rx45-integrity-check ${x.tone}"><small>${esc(x.title)}</small><b>${esc(x.value)}</b><span>${esc(x.detail)}</span></div>`;
   const tableRows=rows.map(r=>`<tr><th scope="row">${esc(r.information)}</th><td data-label="Declarado no CAR">${esc(r.declared)}</td><td data-label="Dentro do perímetro">${esc(r.inside)}</td><td data-label="Medido por nós">${esc(r.measured)}</td></tr>`).join('');
   return `<div class="rx45-integrity-reading ${read.tone}">${esc(read.text)}</div><div class="rx45-integrity-checks">${check(overlap)}${check(municipality)}${check(state)}</div><div class="rx45-integrity-snapshot">Snapshot SICAR: <b>${esc(datePt(d.snapshot))}</b></div><div class="rx45-integrity-scroll"><table class="rx45-integrity-table"><thead><tr><th>Informação</th><th>Declarado no CAR</th><th>Dentro do perímetro</th><th>Medido por nós</th></tr></thead><tbody>${tableRows}</tbody></table></div><div class="rx45-integrity-note">Regeneração = residual geométrico; não comprova regeneração biológica nem conclusão jurídica.</div>`;
 }
 function slot(car){const card=q(`.rx45-panel-card[data-car="${CSS.escape(car)}"]`);if(!card)return null;let s=card.querySelector('.rx45-integrity-slot');if(!s){s=document.createElement('section');s.className='rx45-section rx45-integrity-slot';s.innerHTML='<div class="rx45-integrity-head"><h4 style="margin:0">Consistência CAR</h4><span class="rx45-integrity-badge">Base dos Dados / SICAR</span></div><div class="rx45-integrity-unavailable">Consultando composição e sobreposições…</div>';card.querySelector('.rx45-actions')?.before(s)}return s}
 // F1B: ONE query per opened property. The per-CAR memory of rxPanelSourcesF2 is single-flight (a re-render
 // repaints from memory, never re-queries); a query that did not answer gets ONE automatic retry, then a quiet
 // "Consulta pendente" with "Consultar de novo". Before, four timers (90/720/2300/9800 ms) each fetched again.
 const HEAD='<div class="rx45-integrity-head"><h4 style="margin:0">Consistência CAR</h4><span class="rx45-integrity-badge">Base dos Dados / SICAR</span></div>',SOURCE_ID='car_integrity';
 const pause=ms=>new Promise(r=>setTimeout(r,ms));
 async function query(car,alive,attempts=2){for(let i=0;i<attempts;i++){if(i){await pause(4000);if(!alive())return {abandoned:true}}try{const r=await fetch(`/v1/live/car-integrity/${encodeURIComponent(car)}`,{cache:'no-store'}),d=await r.json();if(r.ok&&d?.ok)return {done:true,data:d}}catch(e){}}return {done:false}}
 function paint(card,e){const s=slot(String(card?.dataset?.car||''));if(!s)return;if(e.phase==='checking'){s.innerHTML=HEAD+'<div class="rx45-integrity-unavailable">Consultando composição e sobreposições…</div>';return}if(e.phase==='done'&&e.data?.ok){s.innerHTML=HEAD+body(e.data);return}s.innerHTML=HEAD+'<div class="rx45-integrity-unavailable rx47-pending-row" data-rx-integrity-pending="1"><span><strong>Consulta pendente</strong><br>A base oficial não respondeu agora. Nenhum resultado foi presumido.</span><button type="button" class="rx45-audit-retry" data-rx47-retry>Consultar de novo</button></div>'}
 function ensure(car){car=String(car||'').trim().toUpperCase();const S=window.rxPanelSourcesF2;if(!car||!S||currentCar()!==car)return;S.settle(SOURCE_ID,car,query,paint)}
 function schedule(car){ensure(car);setTimeout(()=>ensure(car),250)}
 function install(){if(window.rxV47IntegrityInstalled)return;window.rxV47IntegrityInstalled=true;document.addEventListener('rx45:panel-rendered',ev=>ensure(ev?.detail?.car));document.addEventListener('click',e=>{const b=e.target.closest?.('[data-rx47-retry]');if(!b)return;e.preventDefault();const car=String(b.closest('.rx45-panel-card')?.dataset.car||'').trim().toUpperCase(),S=window.rxPanelSourcesF2;if(!car||!S)return;S.forget(SOURCE_ID,car);S.settle(SOURCE_ID,car,(c,alive)=>query(c,alive,1),paint)});const base=window.showProperty;if(typeof base!=='function')return;window.showProperty=function(...args){const out=base.apply(this,args),car=String(args?.[0]?.properties?.cod_imovel||args?.[0]?.properties?.id_imovel||currentCar()||'').trim().toUpperCase();if(car)schedule(car);return out};window.rxV47LoadIntegrity=()=>schedule(currentCar())}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();
</script>
<!-- RX_CAR_INTEGRITY_V47 -->
'''

if "RX_CAR_INTEGRITY_V47" not in portal_v8.PORTAL_HTML:
    portal_v8.PORTAL_HTML = portal_v8.PORTAL_HTML.replace("</body>", V47_INTEGRITY_UI + "</body>")

print("RX_PORTAL_CAR_INTEGRITY_UI_V47=diagnostic_reading_responsive_truth", flush=True)
